# TensorFlow image base written by TensorFlow authors.
# Source: https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/tools/dockerfiles/partials/ubuntu/nvidia.partial.Dockerfile
# -------------------------------------------------------------------------
FROM nvidia/cuda:11.4.0-base-ubuntu20.04 as base

# -------------------------------------------------------------------------
#
# Custom part
FROM base
ARG PYTHON_VERSION=3.9

RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests \
          python${PYTHON_VERSION} \
          python3-pip \
          python${PYTHON_VERSION}-dev \
# Change default python
    && cd /usr/bin \
    && ln -sf python${PYTHON_VERSION}         python3 \
    && ln -sf python${PYTHON_VERSION}m        python3m \
    && ln -sf python${PYTHON_VERSION}-config  python3-config \
    && ln -sf python${PYTHON_VERSION}m-config python3m-config \
    && ln -sf python3                         /usr/bin/python \
# Update pip and add common packages
    && python -m pip install --upgrade pip \
    && python -m pip install --upgrade \
        setuptools \
        wheel \
        six \
# Cleanup
    && apt-get clean \
    && rm -rf $HOME/.cache/pips

# Installs the dependencies located in the requirements.txt
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

# Ensures that Tesseract works, as well as a few other libraries
RUN apt-get update \
        && apt-get install -y \
        ffmpeg libsm6 libxext6  -y \
        build-essential \
        cmake \
        git \
        wget \
        tesseract-ocr \
    && apt-get update

# Sets the current work directory to the projectfolder
WORKDIR /nordjyske-preprocessing

# Copies the training data
COPY ocr/trained_data_files /usr/share/tesseract-ocr/4.00/tessdata



